### ISSUE TITLE
How to download original videos?

### ISSUE THREAD

**Issue by linhanwang** [changwoonchoi/EgoNeRF#1]
Thanks for the awesome work. Could you please provide the original videos?

**Comment by changwoonchoi** [comment]
Hello @linhanwang, thank you for your interest in our work.
We uploaded the original videos of the Ricoh360 dataset in the provided Google Drive directory.
Please refer to it.

**Comment by linhanwang** [comment]
> Hello @linhanwang, thank you for your interest in our work. We uploaded the original videos of the Ricoh360 dataset in the provided Google Drive directory. Please refer to it.

Thank you so much. I never use 360 camera before. It's very interesting to see the videos.
