### ISSUE TITLE
Wondering FPS of rendering

### ISSUE THREAD

**Issue by liquorleaf** [changwoonchoi/EgoNeRF#2]
Dear researcher:

Hi! I have read the paper and consider EgoNeRF an incredible equirectangular image reconstruction method in terms of training speed and novel-view synthesis quality. I would like further seeing the detailed rendering FPS data to consider real-time applications.

Thank you!

**Comment by changwoonchoi** [comment]
The rendering FPS is dependent on various factors.
For example,
- The number of ray sample
- Early termination of ray
- Target resolution

So, it depends on your choice! But, basically, the rendering speed should be similar to TensoRF

**Comment by liquorleaf** [comment]
> The rendering FPS is dependent on various factors. For example,
> 
>     * The number of ray sample
> 
>     * Early termination of ray
> 
>     * Target resolution
> 
> 
> So, it depends on your choice! But, basically, the rendering speed should be similar to TensoRF

Understood! I will try these out with my own application. Thanks again for your cooperation!
